query realtimeData($stops: [String]!) {
  stopPlaces(ids: $stops) {
    id
    name
    estimatedCalls(timeRange: 72100, numberOfDepartures: 10, omitNonBoarding: true) {
      realtime
      aimedDepartureTime
      expectedDepartureTime
      destinationDisplay {
        frontText      
      }
      serviceJourney {
        id
        line {
          id
          transportMode
          publicCode
          presentation {
            colour
            textColour
          }
        }
      }
    }
  }
}